name = "Mission to Mars"
author = "jadelily18"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5257af80b5f9cbb02479ef978d76fbc6af8b81df874fa8d8126aa5cc8378984b"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0-beta.1"
