name = "Mission to Mars"
author = "jadelily18"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01d92cb4860e808f0e725b5c4e3f7125f2c50177ce1be3ad28d868c133c292df"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0-beta.1"
